chem_code      INTEGER,
ai_group       INTEGER,
ago_ind        VARCHAR2(1),
unit_treated   VARCHAR2(1),
mean3sd        NUMBER,
mean5sd        NUMBER,
mean7sd        NUMBER,
mean8sd        NUMBER,
mean10sd       NUMBER,
mean12sd       NUMBER,
mean15sd       NUMBER

ago_ind       VARCHAR2(1),
unit_treated  VARCHAR2(1),
ai_rate_type  VARCHAR2(20),
site_type     VARCHAR2(20),
rate1         NUMBER,
rate2         NUMBER,
rate3         NUMBER,
log_rate1      NUMBER,
log_rate2      NUMBER,
log_rate3      NUMBER

ago_ind        VARCHAR2(1),
unit_treated   VARCHAR2(1),
ai_rate_type   VARCHAR2(20),
site_type      VARCHAR2(20),
fixed2         NUMBER,
mean_limit     VARCHAR2(20)


regno_short     VARCHAR2(20),
ago_ind         VARCHAR2(1),
ai_group        INTEGER,
unit_treated    VARCHAR2(1),
site_general    VARCHAR2(100),
site_type       VARCHAR2(100),
ai_rate_type    VARCHAR2(50),
mean5sd         NUMBER,
mean7sd         NUMBER,
mean8sd         NUMBER,
mean10sd        NUMBER,
mean12sd        NUMBER,
fixed1          NUMBER,
fixed2          NUMBER,
fixed3          NUMBER,
outlier_limit   NUMBER)
